version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: ybank-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ybank_db
      MYSQL_USER: ybank
      MYSQL_PASSWORD: PUlSn2o066nU
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "6013:3306"
    volumes:
      - ybank-data:/var/lib/mysql
    networks:
      - ybank-network

  server:
    image: doxteurn/ynovbank-server:latest
    container_name: ybank-server
    ports:
      - "7011:3333"
    env_file:
      - ./server/.env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ybank-network

  client:
    image: doxteurn/ynovbank-client:latest
    container_name: ybank-client
    ports:
      - "7012:80"
    depends_on:
      - server
    networks:
      - ybank-network

networks:
  ybank-network:
    external: true
    name: ybank-network

volumes:
  ybank-data:
    driver: local
  ybank-temp:
    driver: local
