version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: noco-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: noco_db
      MYSQL_USER: noco
      MYSQL_PASSWORD: PUlSn2o066nU
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "6013:3306"
    volumes:
      - noco-data:/var/lib/mysql
    networks:
      - noco-network

  server:
    image: doxteurn/ynovbank-server:latest
    container_name: noco-server
    ports:
      - "6011:3333"
    env_file:
      - ./server/.env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - noco-network

  client:
    image: doxteurn/ynovbank-client:latest
    container_name: noco-client
    ports:
      - "6012:80"
    depends_on:
      - server
    networks:
      - noco-network

networks:
  noco-network:
    external: true
    name: noco-network

volumes:
  noco-data:
    driver: local
  noco-temp:
    driver: local
